Document: git-aliases
Title: Debian git-aliases Manual
Author: <insert document author here>
Abstract: This manual describes what git-aliases is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/git-aliases/git-aliases.sgml.gz

Format: postscript
Files: /usr/share/doc/git-aliases/git-aliases.ps.gz

Format: text
Files: /usr/share/doc/git-aliases/git-aliases.text.gz

Format: HTML
Index: /usr/share/doc/git-aliases/html/index.html
Files: /usr/share/doc/git-aliases/html/*.html
